exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("menu")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("menu").insert([
        {
          item: "Pear and blue cheese salad",
          rest_id: 1,
          price: 60,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Classic wedge salad",
          rest_id: 1,
          price: 50,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Avocado cucumber salad",
          rest_id: 1,
          price: 30,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Mushroom soup",
          rest_id: 1,
          price: 40,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Courgette fries with spicy chilli mayonnasie",
          rest_id: 1,
          price: 55,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Greek courgette and feta frittata",
          rest_id: 1,
          price: 45,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Vegetarian chicken",
          rest_id: 1,
          price: 110,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Vegetarian wellington",
          rest_id: 1,
          price: 80,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Mushroom buckwheat risotto",
          rest_id: 1,
          price: 95,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Sticky toffee pear pudding",
          rest_id: 1,
          price: 55,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "orange & rhubarb amaretti pots",
          rest_id: 1,
          price: 50,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Lemon cheesecake",
          rest_id: 1,
          price: 50,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Iced tea",
          rest_id: 1,
          price: 30,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Orange juice",
          rest_id: 1,
          price: 30,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Apple juice",
          rest_id: 1,
          price: 30,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "nuts",
          rest_id: 1,
          price: 5,
          category: "others",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Salad with wafu dressing",
          rest_id: 2,
          price: 20,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Japanese potato salad",
          rest_id: 2,
          price: 30,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Japanese kani salad",
          rest_id: 2,
          price: 40,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Chicken wings",
          rest_id: 2,
          price: 30,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Vegetable tempura",
          rest_id: 2,
          price: 40,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Gyoza",
          rest_id: 2,
          price: 20,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Salmon sushi",
          rest_id: 2,
          price: 15,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Sashimi sets",
          rest_id: 2,
          price: 65,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Tamago sushi",
          rest_id: 2,
          price: 15,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Lemon pie",
          rest_id: 2,
          price: 60,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Wagashi",
          rest_id: 2,
          price: 50,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Crepes",
          rest_id: 2,
          price: 50,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Iced coffee",
          rest_id: 2,
          price: 20,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Green tea",
          rest_id: 2,
          price: 18,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Sake",
          rest_id: 2,
          price: 40,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Creamy chicken mushroom soup",
          rest_id: 3,
          price: 20,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Taco soup",
          rest_id: 3,
          price: 30,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Pumpkin",
          rest_id: 3,
          price: 25,
          category: "soup&salad",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Frozen chicken breast",
          rest_id: 3,
          price: 75,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Unchewable garlic bread",
          rest_id: 3,
          price: 75,
          category: "starter",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Steak",
          rest_id: 3,
          price: 85,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Roasted pork",
          rest_id: 3,
          price: 75,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Fried fish",
          rest_id: 3,
          price: 65,
          category: "main",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Ginger pudding",
          rest_id: 3,
          price: 30,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Apple crumbie",
          rest_id: 3,
          price: 30,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Mango cheesecake",
          rest_id: 3,
          price: 30,
          category: "dessert",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Iced lemon tea",
          rest_id: 3,
          price: 15,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Coca cola",
          rest_id: 3,
          price: 20,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
        {
          item: "Iced coffee",
          rest_id: 3,
          price: 15,
          category: "drinks",
          photo_path: "/menu_gallery/placeholder.png",
        },
      ]);
    });
};
